name: Build Automation
on: [push]
jobs:

  build:
    name: Pull upstream source code
    runs-on: ubuntu-latest
    steps:
    - name: Pull source code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                bash ~/bin/update_chromiumOS_source.sh 
